vti_encoding:SR|utf8-nl
vti_author:SR|AESC_NT\\ebiz.aeu
vti_timelastmodified:TR|16 Mar 2011 14:54:04 -0000
vti_timecreated:TR|12 Jan 2010 07:18:04 -0000
vti_lineageid:SR|{B823EBD0-3C0B-445A-AA12-ED6E1C2CAD42}
vti_cacheddtm:TX|12 Jan 2010 07:18:04 -0000
vti_filesize:IR|191277
vti_extenderversion:SR|5.0.2.6790
vti_backlinkinfo:VX|
