'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="MyAdvantechGlobal")>  _
Partial Public Class ACNcustomerDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertACNCustomerFile(instance As ACNCustomerFile)
    End Sub
  Partial Private Sub UpdateACNCustomerFile(instance As ACNCustomerFile)
    End Sub
  Partial Private Sub DeleteACNCustomerFile(instance As ACNCustomerFile)
    End Sub
  Partial Private Sub InsertACNitem(instance As ACNitem)
    End Sub
  Partial Private Sub UpdateACNitem(instance As ACNitem)
    End Sub
  Partial Private Sub DeleteACNitem(instance As ACNitem)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("MyAdvantechGlobalConnectionString2").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ACNCustomerFiles() As System.Data.Linq.Table(Of ACNCustomerFile)
		Get
			Return Me.GetTable(Of ACNCustomerFile)
		End Get
	End Property
	
	Public ReadOnly Property ACNitems() As System.Data.Linq.Table(Of ACNitem)
		Get
			Return Me.GetTable(Of ACNitem)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ACN_Customer_Files")>  _
Partial Public Class ACNCustomerFile
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _CustomerRowid As String
	
	Private _Files As System.Data.Linq.Binary
	
	Private _File_Name As String
	
	Private _File_Ext As String
	
	Private _File_CreateBy As String
	
	Private _File_CreateTime As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnCustomerRowidChanging(value As String)
    End Sub
    Partial Private Sub OnCustomerRowidChanged()
    End Sub
    Partial Private Sub OnFilesChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnFilesChanged()
    End Sub
    Partial Private Sub OnFile_NameChanging(value As String)
    End Sub
    Partial Private Sub OnFile_NameChanged()
    End Sub
    Partial Private Sub OnFile_ExtChanging(value As String)
    End Sub
    Partial Private Sub OnFile_ExtChanged()
    End Sub
    Partial Private Sub OnFile_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnFile_CreateByChanged()
    End Sub
    Partial Private Sub OnFile_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFile_CreateTimeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerRowid", DbType:="VarChar(30)")>  _
	Public Property CustomerRowid() As String
		Get
			Return Me._CustomerRowid
		End Get
		Set
			If (String.Equals(Me._CustomerRowid, value) = false) Then
				Me.OnCustomerRowidChanging(value)
				Me.SendPropertyChanging
				Me._CustomerRowid = value
				Me.SendPropertyChanged("CustomerRowid")
				Me.OnCustomerRowidChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Files", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Files() As System.Data.Linq.Binary
		Get
			Return Me._Files
		End Get
		Set
			If (Object.Equals(Me._Files, value) = false) Then
				Me.OnFilesChanging(value)
				Me.SendPropertyChanging
				Me._Files = value
				Me.SendPropertyChanged("Files")
				Me.OnFilesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_Name", DbType:="NVarChar(200)")>  _
	Public Property File_Name() As String
		Get
			Return Me._File_Name
		End Get
		Set
			If (String.Equals(Me._File_Name, value) = false) Then
				Me.OnFile_NameChanging(value)
				Me.SendPropertyChanging
				Me._File_Name = value
				Me.SendPropertyChanged("File_Name")
				Me.OnFile_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_Ext", DbType:="NVarChar(10)")>  _
	Public Property File_Ext() As String
		Get
			Return Me._File_Ext
		End Get
		Set
			If (String.Equals(Me._File_Ext, value) = false) Then
				Me.OnFile_ExtChanging(value)
				Me.SendPropertyChanging
				Me._File_Ext = value
				Me.SendPropertyChanged("File_Ext")
				Me.OnFile_ExtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property File_CreateBy() As String
		Get
			Return Me._File_CreateBy
		End Get
		Set
			If (String.Equals(Me._File_CreateBy, value) = false) Then
				Me.OnFile_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._File_CreateBy = value
				Me.SendPropertyChanged("File_CreateBy")
				Me.OnFile_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_CreateTime", DbType:="DateTime")>  _
	Public Property File_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._File_CreateTime
		End Get
		Set
			If (Me._File_CreateTime.Equals(value) = false) Then
				Me.OnFile_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._File_CreateTime = value
				Me.SendPropertyChanged("File_CreateTime")
				Me.OnFile_CreateTimeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.ACN_Customer")>  _
Partial Public Class ACNitem
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _RowID As String
	
	Private _sdt_Name As String
	
	Private _sdt_Sort1 As String
	
	Private _sdt_Sort2 As String
	
	Private _sdt_EripID As String
	
	Private _sdt_Title As String
	
	Private _sdt_Telephone As String
	
	Private _sdt_Street As String
	
	Private _sdt_Housenumber As String
	
	Private _sdt_Name_co As String
	
	Private _sdt_Tax1 As String
	
	Private _sdt_bankkey As String
	
	Private _sdt_bankNo As String
	
	Private _sdt_Post As String
	
	Private _sdt_City As String
	
	Private _sdt_Country As String
	
	Private _sdt_Region As String
	
	Private _IsHaveShipto As System.Nullable(Of Integer)
	
	Private _spt_Name As String
	
	Private _spt_Sort1 As String
	
	Private _spt_Sort2 As String
	
	Private _spt_EripID As String
	
	Private _spt_Title As String
	
	Private _spt_Post As String
	
	Private _spt_City As String
	
	Private _spt_Country As String
	
	Private _spt_Region As String
	
	Private _spt_Fax As String
	
	Private _spt_Name_co As String
	
	Private _spt_Telephone As String
	
	Private _spt_MobilePhone As String
	
	Private _spt_Street As String
	
	Private _spt_Housenumber As String
	
	Private _ResquestBy As String
	
	Private _RequestDate As System.Nullable(Of Date)
	
	Private _Status As System.Nullable(Of Integer)
	
	Private _OPerator As String
	
	Private _OPerateDate As System.Nullable(Of Date)
	
	Private _Comment As String
	
	Private _FileDate As System.Data.Linq.Binary
	
	Private _FileExt As String
	
	Private _LAST_UPD_BY As String
	
	Private _LAST_UPD_DATE As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnRowIDChanging(value As String)
    End Sub
    Partial Private Sub OnRowIDChanged()
    End Sub
    Partial Private Sub Onsdt_NameChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_NameChanged()
    End Sub
    Partial Private Sub Onsdt_Sort1Changing(value As String)
    End Sub
    Partial Private Sub Onsdt_Sort1Changed()
    End Sub
    Partial Private Sub Onsdt_Sort2Changing(value As String)
    End Sub
    Partial Private Sub Onsdt_Sort2Changed()
    End Sub
    Partial Private Sub Onsdt_EripIDChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_EripIDChanged()
    End Sub
    Partial Private Sub Onsdt_TitleChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_TitleChanged()
    End Sub
    Partial Private Sub Onsdt_TelephoneChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_TelephoneChanged()
    End Sub
    Partial Private Sub Onsdt_StreetChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_StreetChanged()
    End Sub
    Partial Private Sub Onsdt_HousenumberChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_HousenumberChanged()
    End Sub
    Partial Private Sub Onsdt_Name_coChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_Name_coChanged()
    End Sub
    Partial Private Sub Onsdt_Tax1Changing(value As String)
    End Sub
    Partial Private Sub Onsdt_Tax1Changed()
    End Sub
    Partial Private Sub Onsdt_bankkeyChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_bankkeyChanged()
    End Sub
    Partial Private Sub Onsdt_bankNoChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_bankNoChanged()
    End Sub
    Partial Private Sub Onsdt_PostChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_PostChanged()
    End Sub
    Partial Private Sub Onsdt_CityChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_CityChanged()
    End Sub
    Partial Private Sub Onsdt_CountryChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_CountryChanged()
    End Sub
    Partial Private Sub Onsdt_RegionChanging(value As String)
    End Sub
    Partial Private Sub Onsdt_RegionChanged()
    End Sub
    Partial Private Sub OnIsHaveShiptoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnIsHaveShiptoChanged()
    End Sub
    Partial Private Sub Onspt_NameChanging(value As String)
    End Sub
    Partial Private Sub Onspt_NameChanged()
    End Sub
    Partial Private Sub Onspt_Sort1Changing(value As String)
    End Sub
    Partial Private Sub Onspt_Sort1Changed()
    End Sub
    Partial Private Sub Onspt_Sort2Changing(value As String)
    End Sub
    Partial Private Sub Onspt_Sort2Changed()
    End Sub
    Partial Private Sub Onspt_EripIDChanging(value As String)
    End Sub
    Partial Private Sub Onspt_EripIDChanged()
    End Sub
    Partial Private Sub Onspt_TitleChanging(value As String)
    End Sub
    Partial Private Sub Onspt_TitleChanged()
    End Sub
    Partial Private Sub Onspt_PostChanging(value As String)
    End Sub
    Partial Private Sub Onspt_PostChanged()
    End Sub
    Partial Private Sub Onspt_CityChanging(value As String)
    End Sub
    Partial Private Sub Onspt_CityChanged()
    End Sub
    Partial Private Sub Onspt_CountryChanging(value As String)
    End Sub
    Partial Private Sub Onspt_CountryChanged()
    End Sub
    Partial Private Sub Onspt_RegionChanging(value As String)
    End Sub
    Partial Private Sub Onspt_RegionChanged()
    End Sub
    Partial Private Sub Onspt_FaxChanging(value As String)
    End Sub
    Partial Private Sub Onspt_FaxChanged()
    End Sub
    Partial Private Sub Onspt_Name_coChanging(value As String)
    End Sub
    Partial Private Sub Onspt_Name_coChanged()
    End Sub
    Partial Private Sub Onspt_TelephoneChanging(value As String)
    End Sub
    Partial Private Sub Onspt_TelephoneChanged()
    End Sub
    Partial Private Sub Onspt_MobilePhoneChanging(value As String)
    End Sub
    Partial Private Sub Onspt_MobilePhoneChanged()
    End Sub
    Partial Private Sub Onspt_StreetChanging(value As String)
    End Sub
    Partial Private Sub Onspt_StreetChanged()
    End Sub
    Partial Private Sub Onspt_HousenumberChanging(value As String)
    End Sub
    Partial Private Sub Onspt_HousenumberChanged()
    End Sub
    Partial Private Sub OnResquestByChanging(value As String)
    End Sub
    Partial Private Sub OnResquestByChanged()
    End Sub
    Partial Private Sub OnRequestDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnRequestDateChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnOPeratorChanging(value As String)
    End Sub
    Partial Private Sub OnOPeratorChanged()
    End Sub
    Partial Private Sub OnOPerateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnOPerateDateChanged()
    End Sub
    Partial Private Sub OnCommentChanging(value As String)
    End Sub
    Partial Private Sub OnCommentChanged()
    End Sub
    Partial Private Sub OnFileDateChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnFileDateChanged()
    End Sub
    Partial Private Sub OnFileExtChanging(value As String)
    End Sub
    Partial Private Sub OnFileExtChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanging(value As String)
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RowID", DbType:="VarChar(30) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property RowID() As String
		Get
			Return Me._RowID
		End Get
		Set
			If (String.Equals(Me._RowID, value) = false) Then
				Me.OnRowIDChanging(value)
				Me.SendPropertyChanging
				Me._RowID = value
				Me.SendPropertyChanged("RowID")
				Me.OnRowIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Name", DbType:="NVarChar(150)")>  _
	Public Property sdt_Name() As String
		Get
			Return Me._sdt_Name
		End Get
		Set
			If (String.Equals(Me._sdt_Name, value) = false) Then
				Me.Onsdt_NameChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Name = value
				Me.SendPropertyChanged("sdt_Name")
				Me.Onsdt_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Sort1", DbType:="NVarChar(50)")>  _
	Public Property sdt_Sort1() As String
		Get
			Return Me._sdt_Sort1
		End Get
		Set
			If (String.Equals(Me._sdt_Sort1, value) = false) Then
				Me.Onsdt_Sort1Changing(value)
				Me.SendPropertyChanging
				Me._sdt_Sort1 = value
				Me.SendPropertyChanged("sdt_Sort1")
				Me.Onsdt_Sort1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Sort2", DbType:="NVarChar(50)")>  _
	Public Property sdt_Sort2() As String
		Get
			Return Me._sdt_Sort2
		End Get
		Set
			If (String.Equals(Me._sdt_Sort2, value) = false) Then
				Me.Onsdt_Sort2Changing(value)
				Me.SendPropertyChanging
				Me._sdt_Sort2 = value
				Me.SendPropertyChanged("sdt_Sort2")
				Me.Onsdt_Sort2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_EripID", DbType:="NVarChar(15)")>  _
	Public Property sdt_EripID() As String
		Get
			Return Me._sdt_EripID
		End Get
		Set
			If (String.Equals(Me._sdt_EripID, value) = false) Then
				Me.Onsdt_EripIDChanging(value)
				Me.SendPropertyChanging
				Me._sdt_EripID = value
				Me.SendPropertyChanged("sdt_EripID")
				Me.Onsdt_EripIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Title", DbType:="NVarChar(50)")>  _
	Public Property sdt_Title() As String
		Get
			Return Me._sdt_Title
		End Get
		Set
			If (String.Equals(Me._sdt_Title, value) = false) Then
				Me.Onsdt_TitleChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Title = value
				Me.SendPropertyChanged("sdt_Title")
				Me.Onsdt_TitleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Telephone", DbType:="NVarChar(50)")>  _
	Public Property sdt_Telephone() As String
		Get
			Return Me._sdt_Telephone
		End Get
		Set
			If (String.Equals(Me._sdt_Telephone, value) = false) Then
				Me.Onsdt_TelephoneChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Telephone = value
				Me.SendPropertyChanged("sdt_Telephone")
				Me.Onsdt_TelephoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Street", DbType:="NVarChar(300)")>  _
	Public Property sdt_Street() As String
		Get
			Return Me._sdt_Street
		End Get
		Set
			If (String.Equals(Me._sdt_Street, value) = false) Then
				Me.Onsdt_StreetChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Street = value
				Me.SendPropertyChanged("sdt_Street")
				Me.Onsdt_StreetChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Housenumber", DbType:="NVarChar(150)")>  _
	Public Property sdt_Housenumber() As String
		Get
			Return Me._sdt_Housenumber
		End Get
		Set
			If (String.Equals(Me._sdt_Housenumber, value) = false) Then
				Me.Onsdt_HousenumberChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Housenumber = value
				Me.SendPropertyChanged("sdt_Housenumber")
				Me.Onsdt_HousenumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Name_co", DbType:="NVarChar(50)")>  _
	Public Property sdt_Name_co() As String
		Get
			Return Me._sdt_Name_co
		End Get
		Set
			If (String.Equals(Me._sdt_Name_co, value) = false) Then
				Me.Onsdt_Name_coChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Name_co = value
				Me.SendPropertyChanged("sdt_Name_co")
				Me.Onsdt_Name_coChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Tax1", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property sdt_Tax1() As String
		Get
			Return Me._sdt_Tax1
		End Get
		Set
			If (String.Equals(Me._sdt_Tax1, value) = false) Then
				Me.Onsdt_Tax1Changing(value)
				Me.SendPropertyChanging
				Me._sdt_Tax1 = value
				Me.SendPropertyChanged("sdt_Tax1")
				Me.Onsdt_Tax1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_bankkey", DbType:="NVarChar(50)")>  _
	Public Property sdt_bankkey() As String
		Get
			Return Me._sdt_bankkey
		End Get
		Set
			If (String.Equals(Me._sdt_bankkey, value) = false) Then
				Me.Onsdt_bankkeyChanging(value)
				Me.SendPropertyChanging
				Me._sdt_bankkey = value
				Me.SendPropertyChanged("sdt_bankkey")
				Me.Onsdt_bankkeyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_bankNo", DbType:="NVarChar(50)")>  _
	Public Property sdt_bankNo() As String
		Get
			Return Me._sdt_bankNo
		End Get
		Set
			If (String.Equals(Me._sdt_bankNo, value) = false) Then
				Me.Onsdt_bankNoChanging(value)
				Me.SendPropertyChanging
				Me._sdt_bankNo = value
				Me.SendPropertyChanged("sdt_bankNo")
				Me.Onsdt_bankNoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Post", DbType:="NVarChar(50)")>  _
	Public Property sdt_Post() As String
		Get
			Return Me._sdt_Post
		End Get
		Set
			If (String.Equals(Me._sdt_Post, value) = false) Then
				Me.Onsdt_PostChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Post = value
				Me.SendPropertyChanged("sdt_Post")
				Me.Onsdt_PostChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_City", DbType:="NVarChar(50)")>  _
	Public Property sdt_City() As String
		Get
			Return Me._sdt_City
		End Get
		Set
			If (String.Equals(Me._sdt_City, value) = false) Then
				Me.Onsdt_CityChanging(value)
				Me.SendPropertyChanging
				Me._sdt_City = value
				Me.SendPropertyChanged("sdt_City")
				Me.Onsdt_CityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Country", DbType:="NVarChar(50)")>  _
	Public Property sdt_Country() As String
		Get
			Return Me._sdt_Country
		End Get
		Set
			If (String.Equals(Me._sdt_Country, value) = false) Then
				Me.Onsdt_CountryChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Country = value
				Me.SendPropertyChanged("sdt_Country")
				Me.Onsdt_CountryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sdt_Region", DbType:="NVarChar(50)")>  _
	Public Property sdt_Region() As String
		Get
			Return Me._sdt_Region
		End Get
		Set
			If (String.Equals(Me._sdt_Region, value) = false) Then
				Me.Onsdt_RegionChanging(value)
				Me.SendPropertyChanging
				Me._sdt_Region = value
				Me.SendPropertyChanged("sdt_Region")
				Me.Onsdt_RegionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsHaveShipto", DbType:="Int")>  _
	Public Property IsHaveShipto() As System.Nullable(Of Integer)
		Get
			Return Me._IsHaveShipto
		End Get
		Set
			If (Me._IsHaveShipto.Equals(value) = false) Then
				Me.OnIsHaveShiptoChanging(value)
				Me.SendPropertyChanging
				Me._IsHaveShipto = value
				Me.SendPropertyChanged("IsHaveShipto")
				Me.OnIsHaveShiptoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Name", DbType:="NVarChar(150)")>  _
	Public Property spt_Name() As String
		Get
			Return Me._spt_Name
		End Get
		Set
			If (String.Equals(Me._spt_Name, value) = false) Then
				Me.Onspt_NameChanging(value)
				Me.SendPropertyChanging
				Me._spt_Name = value
				Me.SendPropertyChanged("spt_Name")
				Me.Onspt_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Sort1", DbType:="NVarChar(50)")>  _
	Public Property spt_Sort1() As String
		Get
			Return Me._spt_Sort1
		End Get
		Set
			If (String.Equals(Me._spt_Sort1, value) = false) Then
				Me.Onspt_Sort1Changing(value)
				Me.SendPropertyChanging
				Me._spt_Sort1 = value
				Me.SendPropertyChanged("spt_Sort1")
				Me.Onspt_Sort1Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Sort2", DbType:="NVarChar(50)")>  _
	Public Property spt_Sort2() As String
		Get
			Return Me._spt_Sort2
		End Get
		Set
			If (String.Equals(Me._spt_Sort2, value) = false) Then
				Me.Onspt_Sort2Changing(value)
				Me.SendPropertyChanging
				Me._spt_Sort2 = value
				Me.SendPropertyChanged("spt_Sort2")
				Me.Onspt_Sort2Changed
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_EripID", DbType:="NVarChar(15)")>  _
	Public Property spt_EripID() As String
		Get
			Return Me._spt_EripID
		End Get
		Set
			If (String.Equals(Me._spt_EripID, value) = false) Then
				Me.Onspt_EripIDChanging(value)
				Me.SendPropertyChanging
				Me._spt_EripID = value
				Me.SendPropertyChanged("spt_EripID")
				Me.Onspt_EripIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Title", DbType:="NVarChar(50)")>  _
	Public Property spt_Title() As String
		Get
			Return Me._spt_Title
		End Get
		Set
			If (String.Equals(Me._spt_Title, value) = false) Then
				Me.Onspt_TitleChanging(value)
				Me.SendPropertyChanging
				Me._spt_Title = value
				Me.SendPropertyChanged("spt_Title")
				Me.Onspt_TitleChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Post", DbType:="NVarChar(50)")>  _
	Public Property spt_Post() As String
		Get
			Return Me._spt_Post
		End Get
		Set
			If (String.Equals(Me._spt_Post, value) = false) Then
				Me.Onspt_PostChanging(value)
				Me.SendPropertyChanging
				Me._spt_Post = value
				Me.SendPropertyChanged("spt_Post")
				Me.Onspt_PostChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_City", DbType:="NVarChar(50)")>  _
	Public Property spt_City() As String
		Get
			Return Me._spt_City
		End Get
		Set
			If (String.Equals(Me._spt_City, value) = false) Then
				Me.Onspt_CityChanging(value)
				Me.SendPropertyChanging
				Me._spt_City = value
				Me.SendPropertyChanged("spt_City")
				Me.Onspt_CityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Country", DbType:="NVarChar(50)")>  _
	Public Property spt_Country() As String
		Get
			Return Me._spt_Country
		End Get
		Set
			If (String.Equals(Me._spt_Country, value) = false) Then
				Me.Onspt_CountryChanging(value)
				Me.SendPropertyChanging
				Me._spt_Country = value
				Me.SendPropertyChanged("spt_Country")
				Me.Onspt_CountryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Region", DbType:="NVarChar(50)")>  _
	Public Property spt_Region() As String
		Get
			Return Me._spt_Region
		End Get
		Set
			If (String.Equals(Me._spt_Region, value) = false) Then
				Me.Onspt_RegionChanging(value)
				Me.SendPropertyChanging
				Me._spt_Region = value
				Me.SendPropertyChanged("spt_Region")
				Me.Onspt_RegionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Fax", DbType:="NVarChar(50)")>  _
	Public Property spt_Fax() As String
		Get
			Return Me._spt_Fax
		End Get
		Set
			If (String.Equals(Me._spt_Fax, value) = false) Then
				Me.Onspt_FaxChanging(value)
				Me.SendPropertyChanging
				Me._spt_Fax = value
				Me.SendPropertyChanged("spt_Fax")
				Me.Onspt_FaxChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Name_co", DbType:="NVarChar(100)")>  _
	Public Property spt_Name_co() As String
		Get
			Return Me._spt_Name_co
		End Get
		Set
			If (String.Equals(Me._spt_Name_co, value) = false) Then
				Me.Onspt_Name_coChanging(value)
				Me.SendPropertyChanging
				Me._spt_Name_co = value
				Me.SendPropertyChanged("spt_Name_co")
				Me.Onspt_Name_coChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Telephone", DbType:="NVarChar(50)")>  _
	Public Property spt_Telephone() As String
		Get
			Return Me._spt_Telephone
		End Get
		Set
			If (String.Equals(Me._spt_Telephone, value) = false) Then
				Me.Onspt_TelephoneChanging(value)
				Me.SendPropertyChanging
				Me._spt_Telephone = value
				Me.SendPropertyChanged("spt_Telephone")
				Me.Onspt_TelephoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_MobilePhone", DbType:="NVarChar(50)")>  _
	Public Property spt_MobilePhone() As String
		Get
			Return Me._spt_MobilePhone
		End Get
		Set
			If (String.Equals(Me._spt_MobilePhone, value) = false) Then
				Me.Onspt_MobilePhoneChanging(value)
				Me.SendPropertyChanging
				Me._spt_MobilePhone = value
				Me.SendPropertyChanged("spt_MobilePhone")
				Me.Onspt_MobilePhoneChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Street", DbType:="NVarChar(150) NOT NULL", CanBeNull:=false)>  _
	Public Property spt_Street() As String
		Get
			Return Me._spt_Street
		End Get
		Set
			If (String.Equals(Me._spt_Street, value) = false) Then
				Me.Onspt_StreetChanging(value)
				Me.SendPropertyChanging
				Me._spt_Street = value
				Me.SendPropertyChanged("spt_Street")
				Me.Onspt_StreetChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_spt_Housenumber", DbType:="NVarChar(150)")>  _
	Public Property spt_Housenumber() As String
		Get
			Return Me._spt_Housenumber
		End Get
		Set
			If (String.Equals(Me._spt_Housenumber, value) = false) Then
				Me.Onspt_HousenumberChanging(value)
				Me.SendPropertyChanging
				Me._spt_Housenumber = value
				Me.SendPropertyChanged("spt_Housenumber")
				Me.Onspt_HousenumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ResquestBy", DbType:="NVarChar(100)")>  _
	Public Property ResquestBy() As String
		Get
			Return Me._ResquestBy
		End Get
		Set
			If (String.Equals(Me._ResquestBy, value) = false) Then
				Me.OnResquestByChanging(value)
				Me.SendPropertyChanging
				Me._ResquestBy = value
				Me.SendPropertyChanged("ResquestBy")
				Me.OnResquestByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RequestDate", DbType:="DateTime")>  _
	Public Property RequestDate() As System.Nullable(Of Date)
		Get
			Return Me._RequestDate
		End Get
		Set
			If (Me._RequestDate.Equals(value) = false) Then
				Me.OnRequestDateChanging(value)
				Me.SendPropertyChanging
				Me._RequestDate = value
				Me.SendPropertyChanged("RequestDate")
				Me.OnRequestDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Int")>  _
	Public Property Status() As System.Nullable(Of Integer)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="OPerator", Storage:="_OPerator", DbType:="NVarChar(80)")>  _
	Public Property [OPerator]() As String
		Get
			Return Me._OPerator
		End Get
		Set
			If (String.Equals(Me._OPerator, value) = false) Then
				Me.OnOPeratorChanging(value)
				Me.SendPropertyChanging
				Me._OPerator = value
				Me.SendPropertyChanged("[OPerator]")
				Me.OnOPeratorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OPerateDate", DbType:="DateTime")>  _
	Public Property OPerateDate() As System.Nullable(Of Date)
		Get
			Return Me._OPerateDate
		End Get
		Set
			If (Me._OPerateDate.Equals(value) = false) Then
				Me.OnOPerateDateChanging(value)
				Me.SendPropertyChanging
				Me._OPerateDate = value
				Me.SendPropertyChanged("OPerateDate")
				Me.OnOPerateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comment", DbType:="NVarChar(300)")>  _
	Public Property Comment() As String
		Get
			Return Me._Comment
		End Get
		Set
			If (String.Equals(Me._Comment, value) = false) Then
				Me.OnCommentChanging(value)
				Me.SendPropertyChanging
				Me._Comment = value
				Me.SendPropertyChanged("Comment")
				Me.OnCommentChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FileDate", DbType:="Image", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property FileDate() As System.Data.Linq.Binary
		Get
			Return Me._FileDate
		End Get
		Set
			If (Object.Equals(Me._FileDate, value) = false) Then
				Me.OnFileDateChanging(value)
				Me.SendPropertyChanging
				Me._FileDate = value
				Me.SendPropertyChanged("FileDate")
				Me.OnFileDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FileExt", DbType:="Char(10)")>  _
	Public Property FileExt() As String
		Get
			Return Me._FileExt
		End Get
		Set
			If (String.Equals(Me._FileExt, value) = false) Then
				Me.OnFileExtChanging(value)
				Me.SendPropertyChanging
				Me._FileExt = value
				Me.SendPropertyChanged("FileExt")
				Me.OnFileExtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_BY", DbType:="NVarChar(50)")>  _
	Public Property LAST_UPD_BY() As String
		Get
			Return Me._LAST_UPD_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPD_BY, value) = false) Then
				Me.OnLAST_UPD_BYChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_BY = value
				Me.SendPropertyChanged("LAST_UPD_BY")
				Me.OnLAST_UPD_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_DATE", DbType:="DateTime")>  _
	Public Property LAST_UPD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPD_DATE
		End Get
		Set
			If (Me._LAST_UPD_DATE.Equals(value) = false) Then
				Me.OnLAST_UPD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_DATE = value
				Me.SendPropertyChanged("LAST_UPD_DATE")
				Me.OnLAST_UPD_DATEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
