'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="MyAdvantechGlobal")>  _
Partial Public Class MyCampaignDBDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST(instance As CAMPAIGN_REQUEST)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST(instance As CAMPAIGN_REQUEST)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST(instance As CAMPAIGN_REQUEST)
    End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST_Log(instance As CAMPAIGN_REQUEST_Log)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST_Log(instance As CAMPAIGN_REQUEST_Log)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST_Log(instance As CAMPAIGN_REQUEST_Log)
    End Sub
  Partial Private Sub InsertCAMPAIGN_Request_MarketingManager_RBU(instance As CAMPAIGN_Request_MarketingManager_RBU)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_Request_MarketingManager_RBU(instance As CAMPAIGN_Request_MarketingManager_RBU)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_Request_MarketingManager_RBU(instance As CAMPAIGN_Request_MarketingManager_RBU)
    End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST_MarketingManager(instance As CAMPAIGN_REQUEST_MarketingManager)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST_MarketingManager(instance As CAMPAIGN_REQUEST_MarketingManager)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST_MarketingManager(instance As CAMPAIGN_REQUEST_MarketingManager)
    End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST_TA_Master(instance As CAMPAIGN_REQUEST_TA_Master)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST_TA_Master(instance As CAMPAIGN_REQUEST_TA_Master)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST_TA_Master(instance As CAMPAIGN_REQUEST_TA_Master)
    End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST_TA_Detail(instance As CAMPAIGN_REQUEST_TA_Detail)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST_TA_Detail(instance As CAMPAIGN_REQUEST_TA_Detail)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST_TA_Detail(instance As CAMPAIGN_REQUEST_TA_Detail)
    End Sub
  Partial Private Sub InsertCAMPAIGN_REQUEST_Expand(instance As CAMPAIGN_REQUEST_Expand)
    End Sub
  Partial Private Sub UpdateCAMPAIGN_REQUEST_Expand(instance As CAMPAIGN_REQUEST_Expand)
    End Sub
  Partial Private Sub DeleteCAMPAIGN_REQUEST_Expand(instance As CAMPAIGN_REQUEST_Expand)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("MY").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property CAMPAIGN_REQUESTs() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_REQUEST_Logs() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST_Log)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST_Log)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_Request_MarketingManager_RBUs() As System.Data.Linq.Table(Of CAMPAIGN_Request_MarketingManager_RBU)
		Get
			Return Me.GetTable(Of CAMPAIGN_Request_MarketingManager_RBU)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_REQUEST_MarketingManagers() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST_MarketingManager)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST_MarketingManager)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_REQUEST_TA_Masters() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST_TA_Master)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST_TA_Master)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_REQUEST_TA_Details() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST_TA_Detail)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST_TA_Detail)
		End Get
	End Property
	
	Public ReadOnly Property CAMPAIGN_REQUEST_Expands() As System.Data.Linq.Table(Of CAMPAIGN_REQUEST_Expand)
		Get
			Return Me.GetTable(Of CAMPAIGN_REQUEST_Expand)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST")>  _
Partial Public Class CAMPAIGN_REQUEST
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _REQUESTNO As String
	
	Private _STATUS As System.Nullable(Of Integer)
	
	Private _REQUEST_BY As String
	
	Private _REQUEST_DATE As System.Nullable(Of Date)
	
	Private _COMMENT As String
	
	Private _APPROVED_BY As String
	
	Private _APPROVED_DATE As System.Nullable(Of Date)
	
	Private _REJECTED_BY As String
	
	Private _REJECTED_DATE As System.Nullable(Of Date)
	
	Private _LAST_UPD_BY As String
	
	Private _LAST_UPD_DATE As System.Nullable(Of Date)
	
	Private _CAMPAIGNID As String
	
	Private _ERPID As String
	
	Private _RBU As String
	
	Private _ROLL_OUT_REGION As String
	
	Private _ROLL_OUT_TIME As System.Nullable(Of Date)
	
	Private _TARGET_AUDIENCE As String
	
	Private _PROMOTION_PLAN As String
	
	Private _REQUEST_SUPPORT As String
	
	Private _FEEDBACK As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnREQUESTNOChanging(value As String)
    End Sub
    Partial Private Sub OnREQUESTNOChanged()
    End Sub
    Partial Private Sub OnSTATUSChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUSChanged()
    End Sub
    Partial Private Sub OnREQUEST_BYChanging(value As String)
    End Sub
    Partial Private Sub OnREQUEST_BYChanged()
    End Sub
    Partial Private Sub OnREQUEST_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnREQUEST_DATEChanged()
    End Sub
    Partial Private Sub OnCOMMENTChanging(value As String)
    End Sub
    Partial Private Sub OnCOMMENTChanged()
    End Sub
    Partial Private Sub OnAPPROVED_BYChanging(value As String)
    End Sub
    Partial Private Sub OnAPPROVED_BYChanged()
    End Sub
    Partial Private Sub OnAPPROVED_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnAPPROVED_DATEChanged()
    End Sub
    Partial Private Sub OnREJECTED_BYChanging(value As String)
    End Sub
    Partial Private Sub OnREJECTED_BYChanged()
    End Sub
    Partial Private Sub OnREJECTED_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnREJECTED_DATEChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanging(value As String)
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanged()
    End Sub
    Partial Private Sub OnCAMPAIGNIDChanging(value As String)
    End Sub
    Partial Private Sub OnCAMPAIGNIDChanged()
    End Sub
    Partial Private Sub OnERPIDChanging(value As String)
    End Sub
    Partial Private Sub OnERPIDChanged()
    End Sub
    Partial Private Sub OnRBUChanging(value As String)
    End Sub
    Partial Private Sub OnRBUChanged()
    End Sub
    Partial Private Sub OnROLL_OUT_REGIONChanging(value As String)
    End Sub
    Partial Private Sub OnROLL_OUT_REGIONChanged()
    End Sub
    Partial Private Sub OnROLL_OUT_TIMEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnROLL_OUT_TIMEChanged()
    End Sub
    Partial Private Sub OnTARGET_AUDIENCEChanging(value As String)
    End Sub
    Partial Private Sub OnTARGET_AUDIENCEChanged()
    End Sub
    Partial Private Sub OnPROMOTION_PLANChanging(value As String)
    End Sub
    Partial Private Sub OnPROMOTION_PLANChanged()
    End Sub
    Partial Private Sub OnREQUEST_SUPPORTChanging(value As String)
    End Sub
    Partial Private Sub OnREQUEST_SUPPORTChanged()
    End Sub
    Partial Private Sub OnFEEDBACKChanging(value As String)
    End Sub
    Partial Private Sub OnFEEDBACKChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUESTNO", DbType:="NVarChar(20) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property REQUESTNO() As String
		Get
			Return Me._REQUESTNO
		End Get
		Set
			If (String.Equals(Me._REQUESTNO, value) = false) Then
				Me.OnREQUESTNOChanging(value)
				Me.SendPropertyChanging
				Me._REQUESTNO = value
				Me.SendPropertyChanged("REQUESTNO")
				Me.OnREQUESTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS", DbType:="Int")>  _
	Public Property STATUS() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS
		End Get
		Set
			If (Me._STATUS.Equals(value) = false) Then
				Me.OnSTATUSChanging(value)
				Me.SendPropertyChanging
				Me._STATUS = value
				Me.SendPropertyChanged("STATUS")
				Me.OnSTATUSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUEST_BY", DbType:="NVarChar(50)")>  _
	Public Property REQUEST_BY() As String
		Get
			Return Me._REQUEST_BY
		End Get
		Set
			If (String.Equals(Me._REQUEST_BY, value) = false) Then
				Me.OnREQUEST_BYChanging(value)
				Me.SendPropertyChanging
				Me._REQUEST_BY = value
				Me.SendPropertyChanged("REQUEST_BY")
				Me.OnREQUEST_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUEST_DATE", DbType:="DateTime")>  _
	Public Property REQUEST_DATE() As System.Nullable(Of Date)
		Get
			Return Me._REQUEST_DATE
		End Get
		Set
			If (Me._REQUEST_DATE.Equals(value) = false) Then
				Me.OnREQUEST_DATEChanging(value)
				Me.SendPropertyChanging
				Me._REQUEST_DATE = value
				Me.SendPropertyChanged("REQUEST_DATE")
				Me.OnREQUEST_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMMENT", DbType:="NVarChar(500)")>  _
	Public Property COMMENT() As String
		Get
			Return Me._COMMENT
		End Get
		Set
			If (String.Equals(Me._COMMENT, value) = false) Then
				Me.OnCOMMENTChanging(value)
				Me.SendPropertyChanging
				Me._COMMENT = value
				Me.SendPropertyChanged("COMMENT")
				Me.OnCOMMENTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APPROVED_BY", DbType:="NVarChar(50)")>  _
	Public Property APPROVED_BY() As String
		Get
			Return Me._APPROVED_BY
		End Get
		Set
			If (String.Equals(Me._APPROVED_BY, value) = false) Then
				Me.OnAPPROVED_BYChanging(value)
				Me.SendPropertyChanging
				Me._APPROVED_BY = value
				Me.SendPropertyChanged("APPROVED_BY")
				Me.OnAPPROVED_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_APPROVED_DATE", DbType:="DateTime")>  _
	Public Property APPROVED_DATE() As System.Nullable(Of Date)
		Get
			Return Me._APPROVED_DATE
		End Get
		Set
			If (Me._APPROVED_DATE.Equals(value) = false) Then
				Me.OnAPPROVED_DATEChanging(value)
				Me.SendPropertyChanging
				Me._APPROVED_DATE = value
				Me.SendPropertyChanged("APPROVED_DATE")
				Me.OnAPPROVED_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REJECTED_BY", DbType:="NVarChar(50)")>  _
	Public Property REJECTED_BY() As String
		Get
			Return Me._REJECTED_BY
		End Get
		Set
			If (String.Equals(Me._REJECTED_BY, value) = false) Then
				Me.OnREJECTED_BYChanging(value)
				Me.SendPropertyChanging
				Me._REJECTED_BY = value
				Me.SendPropertyChanged("REJECTED_BY")
				Me.OnREJECTED_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REJECTED_DATE", DbType:="DateTime")>  _
	Public Property REJECTED_DATE() As System.Nullable(Of Date)
		Get
			Return Me._REJECTED_DATE
		End Get
		Set
			If (Me._REJECTED_DATE.Equals(value) = false) Then
				Me.OnREJECTED_DATEChanging(value)
				Me.SendPropertyChanging
				Me._REJECTED_DATE = value
				Me.SendPropertyChanged("REJECTED_DATE")
				Me.OnREJECTED_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_BY", DbType:="NVarChar(50)")>  _
	Public Property LAST_UPD_BY() As String
		Get
			Return Me._LAST_UPD_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPD_BY, value) = false) Then
				Me.OnLAST_UPD_BYChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_BY = value
				Me.SendPropertyChanged("LAST_UPD_BY")
				Me.OnLAST_UPD_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_DATE", DbType:="DateTime")>  _
	Public Property LAST_UPD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPD_DATE
		End Get
		Set
			If (Me._LAST_UPD_DATE.Equals(value) = false) Then
				Me.OnLAST_UPD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_DATE = value
				Me.SendPropertyChanged("LAST_UPD_DATE")
				Me.OnLAST_UPD_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CAMPAIGNID", DbType:="NVarChar(50)")>  _
	Public Property CAMPAIGNID() As String
		Get
			Return Me._CAMPAIGNID
		End Get
		Set
			If (String.Equals(Me._CAMPAIGNID, value) = false) Then
				Me.OnCAMPAIGNIDChanging(value)
				Me.SendPropertyChanging
				Me._CAMPAIGNID = value
				Me.SendPropertyChanged("CAMPAIGNID")
				Me.OnCAMPAIGNIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ERPID", DbType:="NVarChar(20)")>  _
	Public Property ERPID() As String
		Get
			Return Me._ERPID
		End Get
		Set
			If (String.Equals(Me._ERPID, value) = false) Then
				Me.OnERPIDChanging(value)
				Me.SendPropertyChanging
				Me._ERPID = value
				Me.SendPropertyChanged("ERPID")
				Me.OnERPIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RBU", DbType:="NVarChar(20)")>  _
	Public Property RBU() As String
		Get
			Return Me._RBU
		End Get
		Set
			If (String.Equals(Me._RBU, value) = false) Then
				Me.OnRBUChanging(value)
				Me.SendPropertyChanging
				Me._RBU = value
				Me.SendPropertyChanged("RBU")
				Me.OnRBUChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ROLL_OUT_REGION", DbType:="NVarChar(50)")>  _
	Public Property ROLL_OUT_REGION() As String
		Get
			Return Me._ROLL_OUT_REGION
		End Get
		Set
			If (String.Equals(Me._ROLL_OUT_REGION, value) = false) Then
				Me.OnROLL_OUT_REGIONChanging(value)
				Me.SendPropertyChanging
				Me._ROLL_OUT_REGION = value
				Me.SendPropertyChanged("ROLL_OUT_REGION")
				Me.OnROLL_OUT_REGIONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ROLL_OUT_TIME", DbType:="DateTime")>  _
	Public Property ROLL_OUT_TIME() As System.Nullable(Of Date)
		Get
			Return Me._ROLL_OUT_TIME
		End Get
		Set
			If (Me._ROLL_OUT_TIME.Equals(value) = false) Then
				Me.OnROLL_OUT_TIMEChanging(value)
				Me.SendPropertyChanging
				Me._ROLL_OUT_TIME = value
				Me.SendPropertyChanged("ROLL_OUT_TIME")
				Me.OnROLL_OUT_TIMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TARGET_AUDIENCE", DbType:="NVarChar(50)")>  _
	Public Property TARGET_AUDIENCE() As String
		Get
			Return Me._TARGET_AUDIENCE
		End Get
		Set
			If (String.Equals(Me._TARGET_AUDIENCE, value) = false) Then
				Me.OnTARGET_AUDIENCEChanging(value)
				Me.SendPropertyChanging
				Me._TARGET_AUDIENCE = value
				Me.SendPropertyChanged("TARGET_AUDIENCE")
				Me.OnTARGET_AUDIENCEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PROMOTION_PLAN", DbType:="NVarChar(200)")>  _
	Public Property PROMOTION_PLAN() As String
		Get
			Return Me._PROMOTION_PLAN
		End Get
		Set
			If (String.Equals(Me._PROMOTION_PLAN, value) = false) Then
				Me.OnPROMOTION_PLANChanging(value)
				Me.SendPropertyChanging
				Me._PROMOTION_PLAN = value
				Me.SendPropertyChanged("PROMOTION_PLAN")
				Me.OnPROMOTION_PLANChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUEST_SUPPORT", DbType:="NVarChar(200)")>  _
	Public Property REQUEST_SUPPORT() As String
		Get
			Return Me._REQUEST_SUPPORT
		End Get
		Set
			If (String.Equals(Me._REQUEST_SUPPORT, value) = false) Then
				Me.OnREQUEST_SUPPORTChanging(value)
				Me.SendPropertyChanging
				Me._REQUEST_SUPPORT = value
				Me.SendPropertyChanged("REQUEST_SUPPORT")
				Me.OnREQUEST_SUPPORTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FEEDBACK", DbType:="NVarChar(300)")>  _
	Public Property FEEDBACK() As String
		Get
			Return Me._FEEDBACK
		End Get
		Set
			If (String.Equals(Me._FEEDBACK, value) = false) Then
				Me.OnFEEDBACKChanging(value)
				Me.SendPropertyChanging
				Me._FEEDBACK = value
				Me.SendPropertyChanged("FEEDBACK")
				Me.OnFEEDBACKChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST_Log")>  _
Partial Public Class CAMPAIGN_REQUEST_Log
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _REQUESTNO As String
	
	Private _REQUES_STATUS As System.Nullable(Of Integer)
	
	Private _Submitted_by As String
	
	Private _Submitted_date As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnREQUESTNOChanging(value As String)
    End Sub
    Partial Private Sub OnREQUESTNOChanged()
    End Sub
    Partial Private Sub OnREQUES_STATUSChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnREQUES_STATUSChanged()
    End Sub
    Partial Private Sub OnSubmitted_byChanging(value As String)
    End Sub
    Partial Private Sub OnSubmitted_byChanged()
    End Sub
    Partial Private Sub OnSubmitted_dateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnSubmitted_dateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUESTNO", DbType:="NVarChar(20)")>  _
	Public Property REQUESTNO() As String
		Get
			Return Me._REQUESTNO
		End Get
		Set
			If (String.Equals(Me._REQUESTNO, value) = false) Then
				Me.OnREQUESTNOChanging(value)
				Me.SendPropertyChanging
				Me._REQUESTNO = value
				Me.SendPropertyChanged("REQUESTNO")
				Me.OnREQUESTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUES_STATUS", DbType:="Int")>  _
	Public Property REQUES_STATUS() As System.Nullable(Of Integer)
		Get
			Return Me._REQUES_STATUS
		End Get
		Set
			If (Me._REQUES_STATUS.Equals(value) = false) Then
				Me.OnREQUES_STATUSChanging(value)
				Me.SendPropertyChanging
				Me._REQUES_STATUS = value
				Me.SendPropertyChanged("REQUES_STATUS")
				Me.OnREQUES_STATUSChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Submitted_by", DbType:="NVarChar(50)")>  _
	Public Property Submitted_by() As String
		Get
			Return Me._Submitted_by
		End Get
		Set
			If (String.Equals(Me._Submitted_by, value) = false) Then
				Me.OnSubmitted_byChanging(value)
				Me.SendPropertyChanging
				Me._Submitted_by = value
				Me.SendPropertyChanged("Submitted_by")
				Me.OnSubmitted_byChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Submitted_date", DbType:="DateTime")>  _
	Public Property Submitted_date() As System.Nullable(Of Date)
		Get
			Return Me._Submitted_date
		End Get
		Set
			If (Me._Submitted_date.Equals(value) = false) Then
				Me.OnSubmitted_dateChanging(value)
				Me.SendPropertyChanging
				Me._Submitted_date = value
				Me.SendPropertyChanged("Submitted_date")
				Me.OnSubmitted_dateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_Request_MarketingManager_RBU")>  _
Partial Public Class CAMPAIGN_Request_MarketingManager_RBU
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _RBU As String
	
	Private _MarketingManagerID As System.Nullable(Of Integer)
	
	Private _LAST_UPD_BY As String
	
	Private _LAST_UPD_DATE As System.Nullable(Of Date)
	
	Private _CAMPAIGN_REQUEST_MarketingManager As EntityRef(Of CAMPAIGN_REQUEST_MarketingManager)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnRBUChanging(value As String)
    End Sub
    Partial Private Sub OnRBUChanged()
    End Sub
    Partial Private Sub OnMarketingManagerIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMarketingManagerIDChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanging(value As String)
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._CAMPAIGN_REQUEST_MarketingManager = CType(Nothing, EntityRef(Of CAMPAIGN_REQUEST_MarketingManager))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RBU", DbType:="NVarChar(20)")>  _
	Public Property RBU() As String
		Get
			Return Me._RBU
		End Get
		Set
			If (String.Equals(Me._RBU, value) = false) Then
				Me.OnRBUChanging(value)
				Me.SendPropertyChanging
				Me._RBU = value
				Me.SendPropertyChanged("RBU")
				Me.OnRBUChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MarketingManagerID", DbType:="Int")>  _
	Public Property MarketingManagerID() As System.Nullable(Of Integer)
		Get
			Return Me._MarketingManagerID
		End Get
		Set
			If (Me._MarketingManagerID.Equals(value) = false) Then
				If Me._CAMPAIGN_REQUEST_MarketingManager.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnMarketingManagerIDChanging(value)
				Me.SendPropertyChanging
				Me._MarketingManagerID = value
				Me.SendPropertyChanged("MarketingManagerID")
				Me.OnMarketingManagerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_BY", DbType:="NVarChar(50)")>  _
	Public Property LAST_UPD_BY() As String
		Get
			Return Me._LAST_UPD_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPD_BY, value) = false) Then
				Me.OnLAST_UPD_BYChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_BY = value
				Me.SendPropertyChanged("LAST_UPD_BY")
				Me.OnLAST_UPD_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_DATE", DbType:="DateTime")>  _
	Public Property LAST_UPD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPD_DATE
		End Get
		Set
			If (Me._LAST_UPD_DATE.Equals(value) = false) Then
				Me.OnLAST_UPD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_DATE = value
				Me.SendPropertyChanged("LAST_UPD_DATE")
				Me.OnLAST_UPD_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="CAMPAIGN_REQUEST_MarketingManager_CAMPAIGN_Request_MarketingManager_RBU", Storage:="_CAMPAIGN_REQUEST_MarketingManager", ThisKey:="MarketingManagerID", OtherKey:="ID", IsForeignKey:=true)>  _
	Public Property CAMPAIGN_REQUEST_MarketingManager() As CAMPAIGN_REQUEST_MarketingManager
		Get
			Return Me._CAMPAIGN_REQUEST_MarketingManager.Entity
		End Get
		Set
			Dim previousValue As CAMPAIGN_REQUEST_MarketingManager = Me._CAMPAIGN_REQUEST_MarketingManager.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._CAMPAIGN_REQUEST_MarketingManager.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._CAMPAIGN_REQUEST_MarketingManager.Entity = Nothing
					previousValue.CAMPAIGN_Request_MarketingManager_RBUs.Remove(Me)
				End If
				Me._CAMPAIGN_REQUEST_MarketingManager.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.CAMPAIGN_Request_MarketingManager_RBUs.Add(Me)
					Me._MarketingManagerID = value.ID
				Else
					Me._MarketingManagerID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("CAMPAIGN_REQUEST_MarketingManager")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST_MarketingManager")>  _
Partial Public Class CAMPAIGN_REQUEST_MarketingManager
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _BU As String
	
	Private _Responsibility As String
	
	Private _Name As String
	
	Private _Email As String
	
	Private _VOIP As String
	
	Private _Ext As String
	
	Private _CreateBy As String
	
	Private _CreateDate As System.Nullable(Of Date)
	
	Private _LAST_UPD_BY As String
	
	Private _LAST_UPD_DATE As System.Nullable(Of Date)
	
	Private _CAMPAIGN_Request_MarketingManager_RBUs As EntitySet(Of CAMPAIGN_Request_MarketingManager_RBU)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnBUChanging(value As String)
    End Sub
    Partial Private Sub OnBUChanged()
    End Sub
    Partial Private Sub OnResponsibilityChanging(value As String)
    End Sub
    Partial Private Sub OnResponsibilityChanged()
    End Sub
    Partial Private Sub OnNameChanging(value As String)
    End Sub
    Partial Private Sub OnNameChanged()
    End Sub
    Partial Private Sub OnEmailChanging(value As String)
    End Sub
    Partial Private Sub OnEmailChanged()
    End Sub
    Partial Private Sub OnVOIPChanging(value As String)
    End Sub
    Partial Private Sub OnVOIPChanged()
    End Sub
    Partial Private Sub OnExtChanging(value As String)
    End Sub
    Partial Private Sub OnExtChanged()
    End Sub
    Partial Private Sub OnCreateByChanging(value As String)
    End Sub
    Partial Private Sub OnCreateByChanged()
    End Sub
    Partial Private Sub OnCreateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreateDateChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanging(value As String)
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._CAMPAIGN_Request_MarketingManager_RBUs = New EntitySet(Of CAMPAIGN_Request_MarketingManager_RBU)(AddressOf Me.attach_CAMPAIGN_Request_MarketingManager_RBUs, AddressOf Me.detach_CAMPAIGN_Request_MarketingManager_RBUs)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BU", DbType:="NVarChar(50)")>  _
	Public Property BU() As String
		Get
			Return Me._BU
		End Get
		Set
			If (String.Equals(Me._BU, value) = false) Then
				Me.OnBUChanging(value)
				Me.SendPropertyChanging
				Me._BU = value
				Me.SendPropertyChanged("BU")
				Me.OnBUChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Responsibility", DbType:="NVarChar(200)")>  _
	Public Property Responsibility() As String
		Get
			Return Me._Responsibility
		End Get
		Set
			If (String.Equals(Me._Responsibility, value) = false) Then
				Me.OnResponsibilityChanging(value)
				Me.SendPropertyChanging
				Me._Responsibility = value
				Me.SendPropertyChanged("Responsibility")
				Me.OnResponsibilityChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", DbType:="NVarChar(50)")>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me.OnNameChanging(value)
				Me.SendPropertyChanging
				Me._Name = value
				Me.SendPropertyChanged("Name")
				Me.OnNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="NVarChar(50)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me.OnEmailChanging(value)
				Me.SendPropertyChanging
				Me._Email = value
				Me.SendPropertyChanged("Email")
				Me.OnEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VOIP", DbType:="NVarChar(20)")>  _
	Public Property VOIP() As String
		Get
			Return Me._VOIP
		End Get
		Set
			If (String.Equals(Me._VOIP, value) = false) Then
				Me.OnVOIPChanging(value)
				Me.SendPropertyChanging
				Me._VOIP = value
				Me.SendPropertyChanged("VOIP")
				Me.OnVOIPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ext", DbType:="NVarChar(30)")>  _
	Public Property Ext() As String
		Get
			Return Me._Ext
		End Get
		Set
			If (String.Equals(Me._Ext, value) = false) Then
				Me.OnExtChanging(value)
				Me.SendPropertyChanging
				Me._Ext = value
				Me.SendPropertyChanged("Ext")
				Me.OnExtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreateBy", DbType:="NVarChar(50)")>  _
	Public Property CreateBy() As String
		Get
			Return Me._CreateBy
		End Get
		Set
			If (String.Equals(Me._CreateBy, value) = false) Then
				Me.OnCreateByChanging(value)
				Me.SendPropertyChanging
				Me._CreateBy = value
				Me.SendPropertyChanged("CreateBy")
				Me.OnCreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreateDate", DbType:="DateTime")>  _
	Public Property CreateDate() As System.Nullable(Of Date)
		Get
			Return Me._CreateDate
		End Get
		Set
			If (Me._CreateDate.Equals(value) = false) Then
				Me.OnCreateDateChanging(value)
				Me.SendPropertyChanging
				Me._CreateDate = value
				Me.SendPropertyChanged("CreateDate")
				Me.OnCreateDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_BY", DbType:="NVarChar(50)")>  _
	Public Property LAST_UPD_BY() As String
		Get
			Return Me._LAST_UPD_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPD_BY, value) = false) Then
				Me.OnLAST_UPD_BYChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_BY = value
				Me.SendPropertyChanged("LAST_UPD_BY")
				Me.OnLAST_UPD_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_DATE", DbType:="DateTime")>  _
	Public Property LAST_UPD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPD_DATE
		End Get
		Set
			If (Me._LAST_UPD_DATE.Equals(value) = false) Then
				Me.OnLAST_UPD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_DATE = value
				Me.SendPropertyChanged("LAST_UPD_DATE")
				Me.OnLAST_UPD_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="CAMPAIGN_REQUEST_MarketingManager_CAMPAIGN_Request_MarketingManager_RBU", Storage:="_CAMPAIGN_Request_MarketingManager_RBUs", ThisKey:="ID", OtherKey:="MarketingManagerID")>  _
	Public Property CAMPAIGN_Request_MarketingManager_RBUs() As EntitySet(Of CAMPAIGN_Request_MarketingManager_RBU)
		Get
			Return Me._CAMPAIGN_Request_MarketingManager_RBUs
		End Get
		Set
			Me._CAMPAIGN_Request_MarketingManager_RBUs.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_CAMPAIGN_Request_MarketingManager_RBUs(ByVal entity As CAMPAIGN_Request_MarketingManager_RBU)
		Me.SendPropertyChanging
		entity.CAMPAIGN_REQUEST_MarketingManager = Me
	End Sub
	
	Private Sub detach_CAMPAIGN_Request_MarketingManager_RBUs(ByVal entity As CAMPAIGN_Request_MarketingManager_RBU)
		Me.SendPropertyChanging
		entity.CAMPAIGN_REQUEST_MarketingManager = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST_TA_Master")>  _
Partial Public Class CAMPAIGN_REQUEST_TA_Master
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _ListName As String
	
	Private _Description As String
	
	Private _REQUESTNO As String
	
	Private _Status As System.Nullable(Of Integer)
	
	Private _Create_By As String
	
	Private _Create_Date As System.Nullable(Of Date)
	
	Private _LAST_UPD_BY As String
	
	Private _LAST_UPD_DATE As System.Nullable(Of Date)
	
	Private _CAMPAIGN_REQUEST_TA_Details As EntitySet(Of CAMPAIGN_REQUEST_TA_Detail)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnListNameChanging(value As String)
    End Sub
    Partial Private Sub OnListNameChanged()
    End Sub
    Partial Private Sub OnDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnDescriptionChanged()
    End Sub
    Partial Private Sub OnREQUESTNOChanging(value As String)
    End Sub
    Partial Private Sub OnREQUESTNOChanged()
    End Sub
    Partial Private Sub OnStatusChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnStatusChanged()
    End Sub
    Partial Private Sub OnCreate_ByChanging(value As String)
    End Sub
    Partial Private Sub OnCreate_ByChanged()
    End Sub
    Partial Private Sub OnCreate_DateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreate_DateChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanging(value As String)
    End Sub
    Partial Private Sub OnLAST_UPD_BYChanged()
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnLAST_UPD_DATEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._CAMPAIGN_REQUEST_TA_Details = New EntitySet(Of CAMPAIGN_REQUEST_TA_Detail)(AddressOf Me.attach_CAMPAIGN_REQUEST_TA_Details, AddressOf Me.detach_CAMPAIGN_REQUEST_TA_Details)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ListName", DbType:="NVarChar(300)")>  _
	Public Property ListName() As String
		Get
			Return Me._ListName
		End Get
		Set
			If (String.Equals(Me._ListName, value) = false) Then
				Me.OnListNameChanging(value)
				Me.SendPropertyChanging
				Me._ListName = value
				Me.SendPropertyChanged("ListName")
				Me.OnListNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Description", DbType:="NVarChar(100)")>  _
	Public Property Description() As String
		Get
			Return Me._Description
		End Get
		Set
			If (String.Equals(Me._Description, value) = false) Then
				Me.OnDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._Description = value
				Me.SendPropertyChanged("Description")
				Me.OnDescriptionChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_REQUESTNO", DbType:="NVarChar(20)")>  _
	Public Property REQUESTNO() As String
		Get
			Return Me._REQUESTNO
		End Get
		Set
			If (String.Equals(Me._REQUESTNO, value) = false) Then
				Me.OnREQUESTNOChanging(value)
				Me.SendPropertyChanging
				Me._REQUESTNO = value
				Me.SendPropertyChanged("REQUESTNO")
				Me.OnREQUESTNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Status", DbType:="Int")>  _
	Public Property Status() As System.Nullable(Of Integer)
		Get
			Return Me._Status
		End Get
		Set
			If (Me._Status.Equals(value) = false) Then
				Me.OnStatusChanging(value)
				Me.SendPropertyChanging
				Me._Status = value
				Me.SendPropertyChanged("Status")
				Me.OnStatusChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_By", DbType:="NVarChar(50)")>  _
	Public Property Create_By() As String
		Get
			Return Me._Create_By
		End Get
		Set
			If (String.Equals(Me._Create_By, value) = false) Then
				Me.OnCreate_ByChanging(value)
				Me.SendPropertyChanging
				Me._Create_By = value
				Me.SendPropertyChanged("Create_By")
				Me.OnCreate_ByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Create_Date", DbType:="DateTime")>  _
	Public Property Create_Date() As System.Nullable(Of Date)
		Get
			Return Me._Create_Date
		End Get
		Set
			If (Me._Create_Date.Equals(value) = false) Then
				Me.OnCreate_DateChanging(value)
				Me.SendPropertyChanging
				Me._Create_Date = value
				Me.SendPropertyChanged("Create_Date")
				Me.OnCreate_DateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_BY", DbType:="NVarChar(50)")>  _
	Public Property LAST_UPD_BY() As String
		Get
			Return Me._LAST_UPD_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPD_BY, value) = false) Then
				Me.OnLAST_UPD_BYChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_BY = value
				Me.SendPropertyChanged("LAST_UPD_BY")
				Me.OnLAST_UPD_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPD_DATE", DbType:="DateTime")>  _
	Public Property LAST_UPD_DATE() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPD_DATE
		End Get
		Set
			If (Me._LAST_UPD_DATE.Equals(value) = false) Then
				Me.OnLAST_UPD_DATEChanging(value)
				Me.SendPropertyChanging
				Me._LAST_UPD_DATE = value
				Me.SendPropertyChanged("LAST_UPD_DATE")
				Me.OnLAST_UPD_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="CAMPAIGN_REQUEST_TA_Master_CAMPAIGN_REQUEST_TA_Detail", Storage:="_CAMPAIGN_REQUEST_TA_Details", ThisKey:="ID", OtherKey:="TAID")>  _
	Public Property CAMPAIGN_REQUEST_TA_Details() As EntitySet(Of CAMPAIGN_REQUEST_TA_Detail)
		Get
			Return Me._CAMPAIGN_REQUEST_TA_Details
		End Get
		Set
			Me._CAMPAIGN_REQUEST_TA_Details.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_CAMPAIGN_REQUEST_TA_Details(ByVal entity As CAMPAIGN_REQUEST_TA_Detail)
		Me.SendPropertyChanging
		entity.CAMPAIGN_REQUEST_TA_Master = Me
	End Sub
	
	Private Sub detach_CAMPAIGN_REQUEST_TA_Details(ByVal entity As CAMPAIGN_REQUEST_TA_Detail)
		Me.SendPropertyChanging
		entity.CAMPAIGN_REQUEST_TA_Master = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST_TA_Detail")>  _
Partial Public Class CAMPAIGN_REQUEST_TA_Detail
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _Email As String
	
	Private _TAID As System.Nullable(Of Integer)
	
	Private _IsExistSiebel As System.Nullable(Of Boolean)
	
	Private _CAMPAIGN_REQUEST_TA_Master As EntityRef(Of CAMPAIGN_REQUEST_TA_Master)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnEmailChanging(value As String)
    End Sub
    Partial Private Sub OnEmailChanged()
    End Sub
    Partial Private Sub OnTAIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTAIDChanged()
    End Sub
    Partial Private Sub OnIsExistSiebelChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnIsExistSiebelChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._CAMPAIGN_REQUEST_TA_Master = CType(Nothing, EntityRef(Of CAMPAIGN_REQUEST_TA_Master))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="NVarChar(50)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me.OnEmailChanging(value)
				Me.SendPropertyChanging
				Me._Email = value
				Me.SendPropertyChanged("Email")
				Me.OnEmailChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TAID", DbType:="Int")>  _
	Public Property TAID() As System.Nullable(Of Integer)
		Get
			Return Me._TAID
		End Get
		Set
			If (Me._TAID.Equals(value) = false) Then
				If Me._CAMPAIGN_REQUEST_TA_Master.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnTAIDChanging(value)
				Me.SendPropertyChanging
				Me._TAID = value
				Me.SendPropertyChanged("TAID")
				Me.OnTAIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IsExistSiebel", DbType:="Bit")>  _
	Public Property IsExistSiebel() As System.Nullable(Of Boolean)
		Get
			Return Me._IsExistSiebel
		End Get
		Set
			If (Me._IsExistSiebel.Equals(value) = false) Then
				Me.OnIsExistSiebelChanging(value)
				Me.SendPropertyChanging
				Me._IsExistSiebel = value
				Me.SendPropertyChanged("IsExistSiebel")
				Me.OnIsExistSiebelChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="CAMPAIGN_REQUEST_TA_Master_CAMPAIGN_REQUEST_TA_Detail", Storage:="_CAMPAIGN_REQUEST_TA_Master", ThisKey:="TAID", OtherKey:="ID", IsForeignKey:=true)>  _
	Public Property CAMPAIGN_REQUEST_TA_Master() As CAMPAIGN_REQUEST_TA_Master
		Get
			Return Me._CAMPAIGN_REQUEST_TA_Master.Entity
		End Get
		Set
			Dim previousValue As CAMPAIGN_REQUEST_TA_Master = Me._CAMPAIGN_REQUEST_TA_Master.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._CAMPAIGN_REQUEST_TA_Master.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._CAMPAIGN_REQUEST_TA_Master.Entity = Nothing
					previousValue.CAMPAIGN_REQUEST_TA_Details.Remove(Me)
				End If
				Me._CAMPAIGN_REQUEST_TA_Master.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.CAMPAIGN_REQUEST_TA_Details.Add(Me)
					Me._TAID = value.ID
				Else
					Me._TAID = CType(Nothing, Nullable(Of Integer))
				End If
				Me.SendPropertyChanged("CAMPAIGN_REQUEST_TA_Master")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CAMPAIGN_REQUEST_Expand")>  _
Partial Public Class CAMPAIGN_REQUEST_Expand
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ID As Integer
	
	Private _RequestNO As String
	
	Private _Files As System.Data.Linq.Binary
	
	Private _File_Name As String
	
	Private _File_Ext As String
	
	Private _File_CreateBy As String
	
	Private _File_CreateTime As System.Nullable(Of Date)
	
	Private _Promotion_Plan As String
	
	Private _PP_CreateBy As String
	
	Private _PP_CreateTime As System.Nullable(Of Date)
	
	Private _Request_Support As String
	
	Private _RS_CreateBy As String
	
	Private _RS_CreateTime As System.Nullable(Of Date)
	
	Private _Message_Board As String
	
	Private _MS_CreateBy As String
	
	Private _MS_CreateTime As System.Nullable(Of Date)
	
	Private _Message_Board_Answer As String
	
	Private _MSA_CreateBy As String
	
	Private _MSA_CreateTime As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDChanged()
    End Sub
    Partial Private Sub OnRequestNOChanging(value As String)
    End Sub
    Partial Private Sub OnRequestNOChanged()
    End Sub
    Partial Private Sub OnFilesChanging(value As System.Data.Linq.Binary)
    End Sub
    Partial Private Sub OnFilesChanged()
    End Sub
    Partial Private Sub OnFile_NameChanging(value As String)
    End Sub
    Partial Private Sub OnFile_NameChanged()
    End Sub
    Partial Private Sub OnFile_ExtChanging(value As String)
    End Sub
    Partial Private Sub OnFile_ExtChanged()
    End Sub
    Partial Private Sub OnFile_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnFile_CreateByChanged()
    End Sub
    Partial Private Sub OnFile_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnFile_CreateTimeChanged()
    End Sub
    Partial Private Sub OnPromotion_PlanChanging(value As String)
    End Sub
    Partial Private Sub OnPromotion_PlanChanged()
    End Sub
    Partial Private Sub OnPP_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnPP_CreateByChanged()
    End Sub
    Partial Private Sub OnPP_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPP_CreateTimeChanged()
    End Sub
    Partial Private Sub OnRequest_SupportChanging(value As String)
    End Sub
    Partial Private Sub OnRequest_SupportChanged()
    End Sub
    Partial Private Sub OnRS_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnRS_CreateByChanged()
    End Sub
    Partial Private Sub OnRS_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnRS_CreateTimeChanged()
    End Sub
    Partial Private Sub OnMessage_BoardChanging(value As String)
    End Sub
    Partial Private Sub OnMessage_BoardChanged()
    End Sub
    Partial Private Sub OnMS_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnMS_CreateByChanged()
    End Sub
    Partial Private Sub OnMS_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMS_CreateTimeChanged()
    End Sub
    Partial Private Sub OnMessage_Board_AnswerChanging(value As String)
    End Sub
    Partial Private Sub OnMessage_Board_AnswerChanged()
    End Sub
    Partial Private Sub OnMSA_CreateByChanging(value As String)
    End Sub
    Partial Private Sub OnMSA_CreateByChanged()
    End Sub
    Partial Private Sub OnMSA_CreateTimeChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnMSA_CreateTimeChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ID() As Integer
		Get
			Return Me._ID
		End Get
		Set
			If ((Me._ID = value)  _
						= false) Then
				Me.OnIDChanging(value)
				Me.SendPropertyChanging
				Me._ID = value
				Me.SendPropertyChanged("ID")
				Me.OnIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RequestNO", DbType:="NVarChar(20)")>  _
	Public Property RequestNO() As String
		Get
			Return Me._RequestNO
		End Get
		Set
			If (String.Equals(Me._RequestNO, value) = false) Then
				Me.OnRequestNOChanging(value)
				Me.SendPropertyChanging
				Me._RequestNO = value
				Me.SendPropertyChanged("RequestNO")
				Me.OnRequestNOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Files", DbType:="VarBinary(MAX)", UpdateCheck:=UpdateCheck.Never)>  _
	Public Property Files() As System.Data.Linq.Binary
		Get
			Return Me._Files
		End Get
		Set
			If (Object.Equals(Me._Files, value) = false) Then
				Me.OnFilesChanging(value)
				Me.SendPropertyChanging
				Me._Files = value
				Me.SendPropertyChanged("Files")
				Me.OnFilesChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_Name", DbType:="NVarChar(200)")>  _
	Public Property File_Name() As String
		Get
			Return Me._File_Name
		End Get
		Set
			If (String.Equals(Me._File_Name, value) = false) Then
				Me.OnFile_NameChanging(value)
				Me.SendPropertyChanging
				Me._File_Name = value
				Me.SendPropertyChanged("File_Name")
				Me.OnFile_NameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_Ext", DbType:="NVarChar(10)")>  _
	Public Property File_Ext() As String
		Get
			Return Me._File_Ext
		End Get
		Set
			If (String.Equals(Me._File_Ext, value) = false) Then
				Me.OnFile_ExtChanging(value)
				Me.SendPropertyChanging
				Me._File_Ext = value
				Me.SendPropertyChanged("File_Ext")
				Me.OnFile_ExtChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property File_CreateBy() As String
		Get
			Return Me._File_CreateBy
		End Get
		Set
			If (String.Equals(Me._File_CreateBy, value) = false) Then
				Me.OnFile_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._File_CreateBy = value
				Me.SendPropertyChanged("File_CreateBy")
				Me.OnFile_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_File_CreateTime", DbType:="DateTime")>  _
	Public Property File_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._File_CreateTime
		End Get
		Set
			If (Me._File_CreateTime.Equals(value) = false) Then
				Me.OnFile_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._File_CreateTime = value
				Me.SendPropertyChanged("File_CreateTime")
				Me.OnFile_CreateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Promotion_Plan", DbType:="NVarChar(MAX)")>  _
	Public Property Promotion_Plan() As String
		Get
			Return Me._Promotion_Plan
		End Get
		Set
			If (String.Equals(Me._Promotion_Plan, value) = false) Then
				Me.OnPromotion_PlanChanging(value)
				Me.SendPropertyChanging
				Me._Promotion_Plan = value
				Me.SendPropertyChanged("Promotion_Plan")
				Me.OnPromotion_PlanChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PP_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property PP_CreateBy() As String
		Get
			Return Me._PP_CreateBy
		End Get
		Set
			If (String.Equals(Me._PP_CreateBy, value) = false) Then
				Me.OnPP_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._PP_CreateBy = value
				Me.SendPropertyChanged("PP_CreateBy")
				Me.OnPP_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PP_CreateTime", DbType:="DateTime")>  _
	Public Property PP_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._PP_CreateTime
		End Get
		Set
			If (Me._PP_CreateTime.Equals(value) = false) Then
				Me.OnPP_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._PP_CreateTime = value
				Me.SendPropertyChanged("PP_CreateTime")
				Me.OnPP_CreateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Request_Support", DbType:="NVarChar(MAX)")>  _
	Public Property Request_Support() As String
		Get
			Return Me._Request_Support
		End Get
		Set
			If (String.Equals(Me._Request_Support, value) = false) Then
				Me.OnRequest_SupportChanging(value)
				Me.SendPropertyChanging
				Me._Request_Support = value
				Me.SendPropertyChanged("Request_Support")
				Me.OnRequest_SupportChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RS_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property RS_CreateBy() As String
		Get
			Return Me._RS_CreateBy
		End Get
		Set
			If (String.Equals(Me._RS_CreateBy, value) = false) Then
				Me.OnRS_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._RS_CreateBy = value
				Me.SendPropertyChanged("RS_CreateBy")
				Me.OnRS_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RS_CreateTime", DbType:="DateTime")>  _
	Public Property RS_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._RS_CreateTime
		End Get
		Set
			If (Me._RS_CreateTime.Equals(value) = false) Then
				Me.OnRS_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._RS_CreateTime = value
				Me.SendPropertyChanged("RS_CreateTime")
				Me.OnRS_CreateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Message_Board", DbType:="NVarChar(MAX)")>  _
	Public Property Message_Board() As String
		Get
			Return Me._Message_Board
		End Get
		Set
			If (String.Equals(Me._Message_Board, value) = false) Then
				Me.OnMessage_BoardChanging(value)
				Me.SendPropertyChanging
				Me._Message_Board = value
				Me.SendPropertyChanged("Message_Board")
				Me.OnMessage_BoardChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MS_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property MS_CreateBy() As String
		Get
			Return Me._MS_CreateBy
		End Get
		Set
			If (String.Equals(Me._MS_CreateBy, value) = false) Then
				Me.OnMS_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._MS_CreateBy = value
				Me.SendPropertyChanged("MS_CreateBy")
				Me.OnMS_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MS_CreateTime", DbType:="DateTime")>  _
	Public Property MS_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._MS_CreateTime
		End Get
		Set
			If (Me._MS_CreateTime.Equals(value) = false) Then
				Me.OnMS_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._MS_CreateTime = value
				Me.SendPropertyChanged("MS_CreateTime")
				Me.OnMS_CreateTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Message_Board_Answer", DbType:="NVarChar(MAX)")>  _
	Public Property Message_Board_Answer() As String
		Get
			Return Me._Message_Board_Answer
		End Get
		Set
			If (String.Equals(Me._Message_Board_Answer, value) = false) Then
				Me.OnMessage_Board_AnswerChanging(value)
				Me.SendPropertyChanging
				Me._Message_Board_Answer = value
				Me.SendPropertyChanged("Message_Board_Answer")
				Me.OnMessage_Board_AnswerChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MSA_CreateBy", DbType:="NVarChar(80)")>  _
	Public Property MSA_CreateBy() As String
		Get
			Return Me._MSA_CreateBy
		End Get
		Set
			If (String.Equals(Me._MSA_CreateBy, value) = false) Then
				Me.OnMSA_CreateByChanging(value)
				Me.SendPropertyChanging
				Me._MSA_CreateBy = value
				Me.SendPropertyChanged("MSA_CreateBy")
				Me.OnMSA_CreateByChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MSA_CreateTime", DbType:="DateTime")>  _
	Public Property MSA_CreateTime() As System.Nullable(Of Date)
		Get
			Return Me._MSA_CreateTime
		End Get
		Set
			If (Me._MSA_CreateTime.Equals(value) = false) Then
				Me.OnMSA_CreateTimeChanging(value)
				Me.SendPropertyChanging
				Me._MSA_CreateTime = value
				Me.SendPropertyChanged("MSA_CreateTime")
				Me.OnMSA_CreateTimeChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
