'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PIS")>  _
Partial Public Class PISDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("PISConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property PRODUCT_LOGISTICS_NEWs() As System.Data.Linq.Table(Of PRODUCT_LOGISTICS_NEW)
		Get
			Return Me.GetTable(Of PRODUCT_LOGISTICS_NEW)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.PRODUCT_LOGISTICS_NEW")>  _
Partial Public Class PRODUCT_LOGISTICS_NEW
	
	Private _PRODUCT_ID As String
	
	Private _PART_NO As String
	
	Private _PRODUCT_DESC As String
	
	Private _STATUS As String
	
	Private _ORG_ID As String
	
	Private _VERSION As String
	
	Private _UOM As String
	
	Private _MODEL_NO As String
	
	Private _CERTIFICATE As String
	
	Private _PRODUCT_LINE As String
	
	Private _PRODUCT_GROUP As String
	
	Private _TUMBNAIL_IMAGE_ID As String
	
	Private _IMAGE_ID As String
	
	Private _PRODUCT_TYPE As String
	
	Private _ONLINE_PUBLISH As String
	
	Private _EXTENTED_DESC As String
	
	Private _NEW_PRODUCT_DATE As System.Nullable(Of Date)
	
	Private _SHIP_WEIGHT As System.Nullable(Of Decimal)
	
	Private _NET_WEIGHT As System.Nullable(Of Decimal)
	
	Private _PRODUCT_SITE As String
	
	Private _LAST_UPDATED As System.Nullable(Of Date)
	
	Private _LAST_UPDATED_BY As String
	
	Private _CREATED_DATE As System.Nullable(Of Date)
	
	Private _CREATED_BY As String
	
	Private _Controller_Code As String
	
	Private _Cost As System.Nullable(Of Decimal)
	
	Private _Currency As String
	
	Private _RoHS_Status As String
	
	Private _ABC_Ind As String
	
	Private _Region_Dim_Weight As System.Nullable(Of Decimal)
	
	Private _Product_Division As String
	
	Private _Dimension As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_ID", DbType:="VarChar(15)")>  _
	Public Property PRODUCT_ID() As String
		Get
			Return Me._PRODUCT_ID
		End Get
		Set
			If (String.Equals(Me._PRODUCT_ID, value) = false) Then
				Me._PRODUCT_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PART_NO", DbType:="NVarChar(100)")>  _
	Public Property PART_NO() As String
		Get
			Return Me._PART_NO
		End Get
		Set
			If (String.Equals(Me._PART_NO, value) = false) Then
				Me._PART_NO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_DESC", DbType:="NVarChar(255)")>  _
	Public Property PRODUCT_DESC() As String
		Get
			Return Me._PRODUCT_DESC
		End Get
		Set
			If (String.Equals(Me._PRODUCT_DESC, value) = false) Then
				Me._PRODUCT_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS", DbType:="VarChar(30)")>  _
	Public Property STATUS() As String
		Get
			Return Me._STATUS
		End Get
		Set
			If (String.Equals(Me._STATUS, value) = false) Then
				Me._STATUS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORG_ID", DbType:="VarChar(100)")>  _
	Public Property ORG_ID() As String
		Get
			Return Me._ORG_ID
		End Get
		Set
			If (String.Equals(Me._ORG_ID, value) = false) Then
				Me._ORG_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VERSION", DbType:="VarChar(30)")>  _
	Public Property VERSION() As String
		Get
			Return Me._VERSION
		End Get
		Set
			If (String.Equals(Me._VERSION, value) = false) Then
				Me._VERSION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UOM", DbType:="VarChar(30)")>  _
	Public Property UOM() As String
		Get
			Return Me._UOM
		End Get
		Set
			If (String.Equals(Me._UOM, value) = false) Then
				Me._UOM = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODEL_NO", DbType:="NVarChar(100)")>  _
	Public Property MODEL_NO() As String
		Get
			Return Me._MODEL_NO
		End Get
		Set
			If (String.Equals(Me._MODEL_NO, value) = false) Then
				Me._MODEL_NO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CERTIFICATE", DbType:="VarChar(50)")>  _
	Public Property CERTIFICATE() As String
		Get
			Return Me._CERTIFICATE
		End Get
		Set
			If (String.Equals(Me._CERTIFICATE, value) = false) Then
				Me._CERTIFICATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_LINE", DbType:="VarChar(100)")>  _
	Public Property PRODUCT_LINE() As String
		Get
			Return Me._PRODUCT_LINE
		End Get
		Set
			If (String.Equals(Me._PRODUCT_LINE, value) = false) Then
				Me._PRODUCT_LINE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_GROUP", DbType:="VarChar(100)")>  _
	Public Property PRODUCT_GROUP() As String
		Get
			Return Me._PRODUCT_GROUP
		End Get
		Set
			If (String.Equals(Me._PRODUCT_GROUP, value) = false) Then
				Me._PRODUCT_GROUP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TUMBNAIL_IMAGE_ID", DbType:="VarChar(15)")>  _
	Public Property TUMBNAIL_IMAGE_ID() As String
		Get
			Return Me._TUMBNAIL_IMAGE_ID
		End Get
		Set
			If (String.Equals(Me._TUMBNAIL_IMAGE_ID, value) = false) Then
				Me._TUMBNAIL_IMAGE_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IMAGE_ID", DbType:="VarChar(15)")>  _
	Public Property IMAGE_ID() As String
		Get
			Return Me._IMAGE_ID
		End Get
		Set
			If (String.Equals(Me._IMAGE_ID, value) = false) Then
				Me._IMAGE_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_TYPE", DbType:="VarChar(30)")>  _
	Public Property PRODUCT_TYPE() As String
		Get
			Return Me._PRODUCT_TYPE
		End Get
		Set
			If (String.Equals(Me._PRODUCT_TYPE, value) = false) Then
				Me._PRODUCT_TYPE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ONLINE_PUBLISH", DbType:="VarChar(100)")>  _
	Public Property ONLINE_PUBLISH() As String
		Get
			Return Me._ONLINE_PUBLISH
		End Get
		Set
			If (String.Equals(Me._ONLINE_PUBLISH, value) = false) Then
				Me._ONLINE_PUBLISH = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EXTENTED_DESC", DbType:="VarChar(255)")>  _
	Public Property EXTENTED_DESC() As String
		Get
			Return Me._EXTENTED_DESC
		End Get
		Set
			If (String.Equals(Me._EXTENTED_DESC, value) = false) Then
				Me._EXTENTED_DESC = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NEW_PRODUCT_DATE", DbType:="DateTime")>  _
	Public Property NEW_PRODUCT_DATE() As System.Nullable(Of Date)
		Get
			Return Me._NEW_PRODUCT_DATE
		End Get
		Set
			If (Me._NEW_PRODUCT_DATE.Equals(value) = false) Then
				Me._NEW_PRODUCT_DATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SHIP_WEIGHT", DbType:="Decimal(18,2)")>  _
	Public Property SHIP_WEIGHT() As System.Nullable(Of Decimal)
		Get
			Return Me._SHIP_WEIGHT
		End Get
		Set
			If (Me._SHIP_WEIGHT.Equals(value) = false) Then
				Me._SHIP_WEIGHT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NET_WEIGHT", DbType:="Decimal(18,2)")>  _
	Public Property NET_WEIGHT() As System.Nullable(Of Decimal)
		Get
			Return Me._NET_WEIGHT
		End Get
		Set
			If (Me._NET_WEIGHT.Equals(value) = false) Then
				Me._NET_WEIGHT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_SITE", DbType:="VarChar(30)")>  _
	Public Property PRODUCT_SITE() As String
		Get
			Return Me._PRODUCT_SITE
		End Get
		Set
			If (String.Equals(Me._PRODUCT_SITE, value) = false) Then
				Me._PRODUCT_SITE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPDATED", DbType:="DateTime")>  _
	Public Property LAST_UPDATED() As System.Nullable(Of Date)
		Get
			Return Me._LAST_UPDATED
		End Get
		Set
			If (Me._LAST_UPDATED.Equals(value) = false) Then
				Me._LAST_UPDATED = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LAST_UPDATED_BY", DbType:="VarChar(100)")>  _
	Public Property LAST_UPDATED_BY() As String
		Get
			Return Me._LAST_UPDATED_BY
		End Get
		Set
			If (String.Equals(Me._LAST_UPDATED_BY, value) = false) Then
				Me._LAST_UPDATED_BY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATED_DATE", DbType:="DateTime")>  _
	Public Property CREATED_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CREATED_DATE
		End Get
		Set
			If (Me._CREATED_DATE.Equals(value) = false) Then
				Me._CREATED_DATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATED_BY", DbType:="VarChar(100)")>  _
	Public Property CREATED_BY() As String
		Get
			Return Me._CREATED_BY
		End Get
		Set
			If (String.Equals(Me._CREATED_BY, value) = false) Then
				Me._CREATED_BY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Controller_Code", DbType:="NVarChar(50)")>  _
	Public Property Controller_Code() As String
		Get
			Return Me._Controller_Code
		End Get
		Set
			If (String.Equals(Me._Controller_Code, value) = false) Then
				Me._Controller_Code = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Cost", DbType:="Decimal(18,2)")>  _
	Public Property Cost() As System.Nullable(Of Decimal)
		Get
			Return Me._Cost
		End Get
		Set
			If (Me._Cost.Equals(value) = false) Then
				Me._Cost = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Currency", DbType:="VarChar(20)")>  _
	Public Property Currency() As String
		Get
			Return Me._Currency
		End Get
		Set
			If (String.Equals(Me._Currency, value) = false) Then
				Me._Currency = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RoHS_Status", DbType:="VarChar(5)")>  _
	Public Property RoHS_Status() As String
		Get
			Return Me._RoHS_Status
		End Get
		Set
			If (String.Equals(Me._RoHS_Status, value) = false) Then
				Me._RoHS_Status = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ABC_Ind", DbType:="VarChar(5)")>  _
	Public Property ABC_Ind() As String
		Get
			Return Me._ABC_Ind
		End Get
		Set
			If (String.Equals(Me._ABC_Ind, value) = false) Then
				Me._ABC_Ind = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Region_Dim_Weight", DbType:="Decimal(18,0)")>  _
	Public Property Region_Dim_Weight() As System.Nullable(Of Decimal)
		Get
			Return Me._Region_Dim_Weight
		End Get
		Set
			If (Me._Region_Dim_Weight.Equals(value) = false) Then
				Me._Region_Dim_Weight = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Product_Division", DbType:="VarChar(100)")>  _
	Public Property Product_Division() As String
		Get
			Return Me._Product_Division
		End Get
		Set
			If (String.Equals(Me._Product_Division, value) = false) Then
				Me._Product_Division = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Dimension", DbType:="NVarChar(200)")>  _
	Public Property Dimension() As String
		Get
			Return Me._Dimension
		End Get
		Set
			If (String.Equals(Me._Dimension, value) = false) Then
				Me._Dimension = value
			End If
		End Set
	End Property
End Class
