'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


Partial Public Class Quote2OrderPopPNDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property QuoteLists() As System.Data.Linq.Table(Of QuoteList)
		Get
			Return Me.GetTable(Of QuoteList)
		End Get
	End Property
	
	Public ReadOnly Property Quote2Orders() As System.Data.Linq.Table(Of Quote2Order)
		Get
			Return Me.GetTable(Of Quote2Order)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class QuoteList
	
	Private _quoteId As String
	
	Private _quoteNo As String
	
	Private _createdBy As String
	
	Private _salesEmail As String
	
	Private _createdDate As Date
	
	Private _quoteToErpId As String
	
	Private _partNo As String
	
	Private _qty As Integer
	
	Private _MODEL_NO As String
	
	Private _EGROUP As String
	
	Private _EDIVISION As String
	
	Private _PRODUCT_LINE As String
	
	Private _MATERIAL_GROUP As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_quoteId", CanBeNull:=false)>  _
	Public Property quoteId() As String
		Get
			Return Me._quoteId
		End Get
		Set
			If (String.Equals(Me._quoteId, value) = false) Then
				Me._quoteId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_quoteNo", CanBeNull:=false)>  _
	Public Property quoteNo() As String
		Get
			Return Me._quoteNo
		End Get
		Set
			If (String.Equals(Me._quoteNo, value) = false) Then
				Me._quoteNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_createdBy", CanBeNull:=false)>  _
	Public Property createdBy() As String
		Get
			Return Me._createdBy
		End Get
		Set
			If (String.Equals(Me._createdBy, value) = false) Then
				Me._createdBy = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_salesEmail", CanBeNull:=false)>  _
	Public Property salesEmail() As String
		Get
			Return Me._salesEmail
		End Get
		Set
			If (String.Equals(Me._salesEmail, value) = false) Then
				Me._salesEmail = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_createdDate")>  _
	Public Property createdDate() As Date
		Get
			Return Me._createdDate
		End Get
		Set
			If ((Me._createdDate = value)  _
						= false) Then
				Me._createdDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_quoteToErpId", CanBeNull:=false)>  _
	Public Property quoteToErpId() As String
		Get
			Return Me._quoteToErpId
		End Get
		Set
			If (String.Equals(Me._quoteToErpId, value) = false) Then
				Me._quoteToErpId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_partNo", CanBeNull:=false)>  _
	Public Property partNo() As String
		Get
			Return Me._partNo
		End Get
		Set
			If (String.Equals(Me._partNo, value) = false) Then
				Me._partNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_qty")>  _
	Public Property qty() As Integer
		Get
			Return Me._qty
		End Get
		Set
			If ((Me._qty = value)  _
						= false) Then
				Me._qty = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MODEL_NO", CanBeNull:=false)>  _
	Public Property MODEL_NO() As String
		Get
			Return Me._MODEL_NO
		End Get
		Set
			If (String.Equals(Me._MODEL_NO, value) = false) Then
				Me._MODEL_NO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EGROUP", CanBeNull:=false)>  _
	Public Property EGROUP() As String
		Get
			Return Me._EGROUP
		End Get
		Set
			If (String.Equals(Me._EGROUP, value) = false) Then
				Me._EGROUP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EDIVISION", CanBeNull:=false)>  _
	Public Property EDIVISION() As String
		Get
			Return Me._EDIVISION
		End Get
		Set
			If (String.Equals(Me._EDIVISION, value) = false) Then
				Me._EDIVISION = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PRODUCT_LINE", CanBeNull:=false)>  _
	Public Property PRODUCT_LINE() As String
		Get
			Return Me._PRODUCT_LINE
		End Get
		Set
			If (String.Equals(Me._PRODUCT_LINE, value) = false) Then
				Me._PRODUCT_LINE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MATERIAL_GROUP", CanBeNull:=false)>  _
	Public Property MATERIAL_GROUP() As String
		Get
			Return Me._MATERIAL_GROUP
		End Get
		Set
			If (String.Equals(Me._MATERIAL_GROUP, value) = false) Then
				Me._MATERIAL_GROUP = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class Quote2Order
	
	Private _QUOTEID As String
	
	Private _SO_NO As String
	
	Private _ORDER_DATE As Date
	
	Private _ORDER_BY As String
	
	Private _COMPANY_ID As String
	
	Private _PART_NO As String
	
	Private _UNIT_PRICE As Decimal
	
	Private _CURRENCY As String
	
	Private _US_AMT As Decimal
	
	Private _ORDER_QTY As Decimal
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_QUOTEID", CanBeNull:=false)>  _
	Public Property QUOTEID() As String
		Get
			Return Me._QUOTEID
		End Get
		Set
			If (String.Equals(Me._QUOTEID, value) = false) Then
				Me._QUOTEID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SO_NO", CanBeNull:=false)>  _
	Public Property SO_NO() As String
		Get
			Return Me._SO_NO
		End Get
		Set
			If (String.Equals(Me._SO_NO, value) = false) Then
				Me._SO_NO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_DATE")>  _
	Public Property ORDER_DATE() As Date
		Get
			Return Me._ORDER_DATE
		End Get
		Set
			If ((Me._ORDER_DATE = value)  _
						= false) Then
				Me._ORDER_DATE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_BY", CanBeNull:=false)>  _
	Public Property ORDER_BY() As String
		Get
			Return Me._ORDER_BY
		End Get
		Set
			If (String.Equals(Me._ORDER_BY, value) = false) Then
				Me._ORDER_BY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_COMPANY_ID", CanBeNull:=false)>  _
	Public Property COMPANY_ID() As String
		Get
			Return Me._COMPANY_ID
		End Get
		Set
			If (String.Equals(Me._COMPANY_ID, value) = false) Then
				Me._COMPANY_ID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PART_NO", CanBeNull:=false)>  _
	Public Property PART_NO() As String
		Get
			Return Me._PART_NO
		End Get
		Set
			If (String.Equals(Me._PART_NO, value) = false) Then
				Me._PART_NO = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UNIT_PRICE")>  _
	Public Property UNIT_PRICE() As Decimal
		Get
			Return Me._UNIT_PRICE
		End Get
		Set
			If ((Me._UNIT_PRICE = value)  _
						= false) Then
				Me._UNIT_PRICE = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CURRENCY", CanBeNull:=false)>  _
	Public Property CURRENCY() As String
		Get
			Return Me._CURRENCY
		End Get
		Set
			If (String.Equals(Me._CURRENCY, value) = false) Then
				Me._CURRENCY = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_US_AMT")>  _
	Public Property US_AMT() As Decimal
		Get
			Return Me._US_AMT
		End Get
		Set
			If ((Me._US_AMT = value)  _
						= false) Then
				Me._US_AMT = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ORDER_QTY")>  _
	Public Property ORDER_QTY() As Decimal
		Get
			Return Me._ORDER_QTY
		End Get
		Set
			If ((Me._ORDER_QTY = value)  _
						= false) Then
				Me._ORDER_QTY = value
			End If
		End Set
	End Property
End Class
